networks:
  gosh:
    endpoint: "network.gosh.sh"
    values: &vals
      - 31000
      - 15
      - 20
      - 17
      - 16
      - 2
      - 1.4
      - 1.6
      - 6
      - 1.3
      - 18
      - 60
      - ^31000
      - ^60
  test:
    endpoint: "vps23.ton.dev"
    values: *vals
