version: '3'

networks:
  gosh-monitoring:
    external:
      name: gosh-monitoring
  gosh-public-grafana:
    external:
      name: gosh-public-grafana


services:

  gosh-caddy:
    image: caddy:2.5.2
    container_name: gosh-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy
      - ./data:/data
      - ./www:/var/www
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
      - HOST_NAME=${HOST_NAME:-monitoring}
      - PUBLIC_GRAFANA=${PUBLIC_GRAFANA}
      - MONITORING_DOMAIN=${MONITORING_DOMAIN}
    restart: unless-stopped
    networks:
      - gosh-monitoring
      - gosh-public-grafana
