trigger:
- azure-pipelines

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
- script: |
    mkdir -p ./resources \
    cp ../contracts/gosh/*.abi.json ./resources/ \
    cargo build --release
