name: git-remote-gosh
base: core20
version: VERSION_PLACEHOLDER
summary: Git Open Source Hodler
description: |
  A scalable solution reducing the risks and resources spent on protecting code, and moving open source up the value chain.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
  
parts:
  git-remote-gosh:
    plugin: dump
    source: ./git-remote-gosh.tar

apps:
  git-remote-gosh:
    command: git-remote-gosh 
