{
 "title": "Gosh Monitoring dev details",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Dynamic gosh-mon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Test execution result (error level)",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Test value result (read last write)",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "gosh_mon_result{mode!~\".+-next\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "time() - gosh_mon_value{mode=~\".+-small-read\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "time() - gosh_mon_value{mode=~\".+-large-read\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "gosh_mon_result{mode=~\".+-next\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "time() - gosh_mon_value{mode=~\".+-small-read-next\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "time() - gosh_mon_value{mode=~\".+-large-read-next\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Last read",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - gosh_mon_timestamp{mode=~\".+-read(-next)?\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Last write (small)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - gosh_mon_timestamp{mode=~\".+-small-write(-next)?\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Last write (large)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - gosh_mon_timestamp{mode=~\".+-large-write(-next)?\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Last read check duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gosh_mon_duration{mode=~\".+-read(-next)?\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Last write check duration (small)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gosh_mon_duration{mode=~\".+-small-write(-next)?\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Last write check duration (large)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gosh_mon_duration{mode=~\".+-large-write(-next)?\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Small reads value behind",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "time() - gosh_mon_value{mode=~\".+-small-read(-next)?\"} < 1000000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Large reads value behind",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "time() - gosh_mon_value{mode=~\".+-large-read(-next)?\"} < 1000000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Logs counter monitoring",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "sha_incorrect occurrences ",
   "type": "state-timeline",
   "description": "It is a sequence of changes. Sha must be correct. Fail otherwise",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "gosh_mon_log_count{item=\"sha_incorrect\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "none_unwrap occurrences ",
   "type": "state-timeline",
   "description": "thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value'",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "gosh_mon_log_count{item=\"none_unwrap\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "exec_timeout occurrences ",
   "type": "state-timeline",
   "description": "Exited with code null",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "gosh_mon_log_count{item=\"exec_timeout\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}