{
 "title": "Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "net",
    "label": "Network",
    "query": "Production : gosh, Testing : test"
   }
  ]
 },
 "panels": [
  { "title": "Numbers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Production network",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trcnt_stat_res{network=\"gosh\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "modifiers.sol",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": {
    "content": "<pre>\n    uint128 constant FEE_DEPLOY_DAO = 31000 ton;\n    uint128 constant FEE_DEPLOY_REPO = 15 ton;\n    uint128 constant FEE_DEPLOY_COMMIT = 20 ton;\n    uint128 constant FEE_DEPLOY_DIFF = 17 ton;\n    uint128 constant FEE_DEPLOY_SNAPSHOT = 16 ton;\n    uint128 constant FEE_DEPLOY_COPY_SNAPSHOT = 2 ton;\n    uint128 constant FEE_DEPLOY_BRANCH = 1.4 ton;\n    uint128 constant FEE_DESTROY_BRANCH = 1.6 ton;\n    uint128 constant FEE_DEPLOY_TAG = 6 ton;\n    uint128 constant FEE_DESTROY_TAG = 1.3 ton;\n    uint128 constant FEE_DEPLOY_TREE = 18 ton;\n    uint128 constant FEE_DEPLOY_WALLET = 60 ton;\n</pre>"
   }
  },
  {
   "title": "Test network",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trcnt_stat_res{network=\"test\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Production delta 1h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{network=\"gosh\"}[1h])",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Production delta 1d",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{network=\"gosh\"}[1d])",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Test delta 1h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{network=\"test\"}[1h])",
     "legendFormat": "{{range}}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "DAOs",
   "type": "timeseries",
   "description": "^31000",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"^31000\",network=~\"$net\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Wallets",
   "type": "timeseries",
   "description": "^60",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"^60\",network=~\"$net\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "timeseries",
   "description": "15",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"15\",network=~\"$net\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "timeseries",
   "description": "20",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"20\",network=~\"$net\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Diffs",
   "type": "timeseries",
   "description": "17",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"17\",network=~\"$net\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "timeseries",
   "description": "16",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"16\",network=~\"$net\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Copy Snapshots",
   "type": "timeseries",
   "description": "2",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"2\",network=~\"$net\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Deploy Branches",
   "type": "timeseries",
   "description": "1.4",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"1.4\",network=~\"$net\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Destroy Branches",
   "type": "timeseries",
   "description": "1.6",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"1.6\",network=~\"$net\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Deploy Tags",
   "type": "timeseries",
   "description": "6",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"6\",network=~\"$net\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Destroy Tags",
   "type": "timeseries",
   "description": "1.3",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"1.3\",network=~\"$net\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Trees",
   "type": "timeseries",
   "description": "18",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"18\",network=~\"$net\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  { "title": "Delta 1d", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "DAOs",
   "type": "timeseries",
   "description": "^31000",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"^31000\",network=~\"$net\"}[1d])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Wallets",
   "type": "timeseries",
   "description": "^60",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"^60\",network=~\"$net\"}[1d])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "timeseries",
   "description": "15",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"15\",network=~\"$net\"}[1d])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "timeseries",
   "description": "20",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"20\",network=~\"$net\"}[1d])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Diffs",
   "type": "timeseries",
   "description": "17",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"17\",network=~\"$net\"}[1d])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "timeseries",
   "description": "16",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"16\",network=~\"$net\"}[1d])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Copy Snapshots",
   "type": "timeseries",
   "description": "2",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"2\",network=~\"$net\"}[1d])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Deploy Branches",
   "type": "timeseries",
   "description": "1.4",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"1.4\",network=~\"$net\"}[1d])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Destroy Branches",
   "type": "timeseries",
   "description": "1.6",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"1.6\",network=~\"$net\"}[1d])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Deploy Tags",
   "type": "timeseries",
   "description": "6",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"6\",network=~\"$net\"}[1d])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Destroy Tags",
   "type": "timeseries",
   "description": "1.3",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"1.3\",network=~\"$net\"}[1d])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Trees",
   "type": "timeseries",
   "description": "18",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"18\",network=~\"$net\"}[1d])",
     "legendFormat": "{{network}}"
    }
   ]
  }
 ]
}