{
 "title": "Wallet balances monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Root and creator contracts", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Main network gosh root token balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "wallet_mon_balance{network=\"gosh\",name=\"root\"} / 1000000000",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 18, "w": 2, "x": 11, "y": 1 } },
  {
   "title": "Test network gosh root token balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "wallet_mon_balance{network=\"test\",name=\"root\"} / 1000000000",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Main network gosh creator token balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "wallet_mon_balance{network=\"gosh\",name=\"creator\"} / 1000000000",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Test network gosh creator token balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "expr": "wallet_mon_balance{network=\"test\",name=\"creator\"} / 1000000000",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  { "title": "System contracts", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Main network -1:0 token balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "wallet_mon_balance{network=\"gosh\",name=\"zero\"} / 1000000000",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 27, "w": 2, "x": 11, "y": 20 } },
  {
   "title": "Test network -1:0 token balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "expr": "wallet_mon_balance{network=\"test\",name=\"zero\"} / 1000000000",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Main network -1:2 token balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "wallet_mon_balance{network=\"gosh\",name=\"extra\"} / 1000000000",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Test network -1:2 token balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 29 },
   "targets": [
    {
     "expr": "wallet_mon_balance{network=\"test\",name=\"extra\"} / 1000000000",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Main network -1:7 token balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "wallet_mon_balance{network=\"gosh\",name=\"giver\"} / 1000000000",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Test network -1:7 token balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 38 },
   "targets": [
    {
     "expr": "wallet_mon_balance{network=\"test\",name=\"giver\"} / 1000000000",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Extra currencies (other balance)",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Main network extra currency balances",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 11, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "wallet_mon_balance_other{network=\"gosh\"}",
     "legendFormat": "{{addr}} ({{currency}})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 18, "w": 2, "x": 11, "y": 48 } },
  {
   "title": "Test network extra currency balances",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 11, "x": 13, "y": 48 },
   "targets": [
    {
     "expr": "wallet_mon_balance_other{network=\"test\"}",
     "legendFormat": "{{addr}} ({{currency}})"
    }
   ]
  }
 ]
}