version: '3'

networks:
  gosh-public-grafana:
    external:
      name: gosh-public-grafana

services:

  gosh-public-grafana:
    image: grafana/grafana:9.1.2
    container_name: gosh-public-grafana
    volumes:
      - ./data:/var/lib/grafana
      - ./grafana:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/gosh/home.json
      - HTTPS_PROXY=http://gosh-prom-filter-proxy:8899/
      - HTTP_PROXY=http://gosh-prom-filter-proxy:8899/
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - gosh-public-grafana
    labels:
      org.label-schema.group: "gosh-monitoring"

