cp ../../../v1_x/contracts/profile.abi.json ./blockchain/abi/profile.abi.json
cp ../../../v1_x/contracts/gosh/commit.abi.json ./blockchain/abi/commit.abi.json
cp ../../../v1_x/contracts/gosh/tag.abi.json ./blockchain/abi/committag.abi.json
cp ../../../v1_x/contracts/gosh/goshdao.abi.json ./blockchain/abi/dao.abi.json
cp ../../../v1_x/contracts/gosh/goshwallet.abi.json ./blockchain/abi/daowallet.abi.json
cp ../../../v1_x/contracts/gosh/repository.abi.json ./blockchain/abi/repository.abi.json
cp ../../../v1_x/contracts/gosh/snapshot.abi.json ./blockchain/abi/snapshot.abi.json
cp ../../../v1_x/contracts/gosh/systemcontract.abi.json ./blockchain/abi/systemcontract.abi.json
cp ../../../v1_x/contracts/smv/SMVClient.abi.json ./blockchain/abi/smvclient.abi.json
cp ../../../v1_x/contracts/smv/SMVProposal.abi.json ./blockchain/abi/smvproposal.abi.json
cp ../../../v1_x/contracts/smv/SMVTokenLocker.abi.json ./blockchain/abi/smvtokenlocker.abi.json