{
 "title": "New GOSH Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "net", "label": "Network", "query": "gosh" }
  ]
 },
 "panels": [
  { "title": "Upload queue (onboarding)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repositories: count change during selected time range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(supa_tele_repositories_uploaded[$__range])",
     "legendFormat": "Uploaded"
    },
    {
     "expr": "delta(supa_tele_repositories_total[$__range])",
     "legendFormat": "Total"
    },
    {
     "expr": "delta(supa_tele_repositories_total[$__range]) - delta(supa_tele_repositories_uploaded[$__range])",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Repositories (counts)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "supa_tele_repositories_uploaded",
     "legendFormat": "Uploaded"
    },
    { "expr": "supa_tele_repositories_total", "legendFormat": "Total" },
    {
     "expr": "supa_tele_repositories_total - supa_tele_repositories_uploaded",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Repositories (stacked graph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "supa_tele_repositories_uploaded",
     "legendFormat": "Uploaded"
    },
    {
     "expr": "supa_tele_repositories_total - supa_tele_repositories_uploaded",
     "legendFormat": "Remaining"
    },
    { "expr": "supa_tele_repositories_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Registrations: count change during selected time range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(supa_tele_daos_total[$__range])",
     "legendFormat": "DAOs"
    },
    {
     "expr": "delta(supa_tele_users_total[$__range])",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Registrations (counts)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "supa_tele_daos_total", "legendFormat": "DAOs" },
    { "expr": "supa_tele_users_total", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Registrations (overlayed graph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    { "expr": "supa_tele_daos_total", "legendFormat": "DAOs" },
    { "expr": "supa_tele_users_total", "legendFormat": "Users" }
   ]
  },
  { "title": "Count by code hash", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Count change during selected time range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_chres{tag=~\"daoprof-.*\",network=\"$net\"}[$__range])",
     "legendFormat": " DAOs"
    },
    {
     "expr": "delta(trcnt_stat_chres{tag=~\"userprof-.*\",network=\"$net\"}[$__range])",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Count all deployed contracts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trcnt_stat_chres{tag=~\"daoprof-.*\",network=\"$net\"}",
     "legendFormat": " DAOs"
    },
    {
     "expr": "trcnt_stat_chres{tag=~\"userprof-.*\",network=\"$net\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Deployed contracts (overlayed graph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "trcnt_stat_chres{tag=~\"daoprof-.*\",network=\"$net\"}",
     "legendFormat": "DAOs"
    },
    {
     "expr": "trcnt_stat_chres{tag=~\"userprof-.*\",network=\"$net\"}",
     "legendFormat": "Users"
    }
   ]
  },
  { "title": "Count by transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "New objects during selected time range",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Organizations (DAOs)",
   "type": "stat",
   "description": "101",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"101\",network=\"$net\"}[$__range])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "description": "15",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"15\",network=\"$net\"}[$__range])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Commits",
   "type": "stat",
   "description": "20",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"20\",network=\"$net\"}[$__range])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Diffs",
   "type": "stat",
   "description": "17",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"17\",network=\"$net\"}[$__range])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "stat",
   "description": "16 + 50",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(trcnt_stat_res{range=~\"16|50\",network=\"$net\"}[$__range]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Branches",
   "type": "stat",
   "description": "1.4",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"1.4\",network=\"$net\"}[$__range])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Trees",
   "type": "stat",
   "description": "18",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"18\",network=\"$net\"}[$__range])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Wallets",
   "type": "stat",
   "description": "^60 + ^1000",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(trcnt_stat_res{range=~\"(\\\\^60|\\\\^1000)\",network=\"$net\"}[$__range]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Tags",
   "type": "stat",
   "description": "6",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"6\",network=\"$net\"}[$__range])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Profiles",
   "type": "stat",
   "description": "^10000",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=\"10000\",network=\"$net\"}[$__range])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total by all contract types",
   "type": "stat",
   "description": "101 + 15 + 20 + 17 + 16 + 50 + 1.4 + 18 + ^60 + ^1000 + 6 + 10000",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(trcnt_stat_res{range=~\"(101|15|20|17|16|50|1\\\\.4|18|\\\\^60|\\\\^1000|6|10000)\",network=\"$net\"}[$__range]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total by all contract types",
   "type": "piechart",
   "description": "101 + 15 + 20 + 17 + 16 + 50 + 1.4 + 18 + ^60 + ^1000 + 6 + 10000",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(trcnt_stat_res{range=~\"(101|15|20|17|16|50|1\\\\.4|18|\\\\^60|\\\\^1000|6|10000)\",network=\"$net\"}[$__range])",
     "legendFormat": "{{range}}"
    }
   ]
  },
  { "title": "Total amount of objects", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Organizations (DAOs)",
   "type": "timeseries",
   "description": "101",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"101\",network=\"$net\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "timeseries",
   "description": "15",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"15\",network=\"$net\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Commits",
   "type": "timeseries",
   "description": "20",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"20\",network=\"$net\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Diffs",
   "type": "timeseries",
   "description": "17",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"17\",network=\"$net\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Created snapshots",
   "type": "timeseries",
   "description": "16 + 50",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(trcnt_stat_res{range=~\"(16|50)\",network=\"$net\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Created branches",
   "type": "timeseries",
   "description": "1.4",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"1.4\",network=\"$net\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Created trees",
   "type": "timeseries",
   "description": "18",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"18\",network=\"$net\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Created wallets",
   "type": "timeseries",
   "description": "^60 + ^1000",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(trcnt_stat_res{range=~\"(\\\\^60|\\\\^1000)\",network=\"$net\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Tags",
   "type": "timeseries",
   "description": "6",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"6\",network=\"$net\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Profiles",
   "type": "timeseries",
   "description": "10000",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=\"10000\",network=\"$net\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total by all contract types",
   "type": "timeseries",
   "description": "101 + 15 + 20 + 17 + 16 + 50 + 1.4 + 18 + ^60 + ^1000 + 6 + 10000",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=~\"(101|15|20|17|16|50|1\\\\.4|18|\\\\^60|\\\\^1000|6|10000)\",network=\"$net\"}",
     "legendFormat": "{{range}}"
    },
    {
     "expr": "sum(trcnt_stat_res{range=~\"(101|15|20|17|16|50|1\\\\.4|18|\\\\^60|\\\\^1000|6|10000)\",network=\"$net\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total by all contract types",
   "type": "piechart",
   "description": "101 + 15 + 20 + 17 + 16 + 50 + 1.4 + 18 + ^60 + ^1000 + 6 + 10000",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trcnt_stat_res{range=~\"(101|15|20|17|16|50|1\\\\.4|18|\\\\^60|\\\\^1000|6|10000)\",network=\"$net\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  { "title": "End-to-end tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "End to end realtime tests status",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "gosh_mon_result{mode!~\".+-next\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Last written seconds ago (small files)",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "time() - gosh_mon_value{mode=~\".+-small-read\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Last written seconds ago (large files)",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "time() - gosh_mon_value{mode=~\".+-large-read\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": " ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Organizations (DAOs)",
     "type": "stat",
     "description": "^31000 + ^50000",
     "gridPos": { "h": 1, "w": 1, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(trcnt_stat_res{range=~\"(\\\\^31000|\\\\^50000)\",network=\"$net\"}[$__range]))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Profile indexes",
     "type": "stat",
     "description": "3",
     "gridPos": { "h": 1, "w": 1, "x": 1, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(trcnt_stat_res{range=\"3\",network=\"$net\"}[$__range])",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Organizations (DAOs)",
     "type": "timeseries",
     "description": "^31000 + ^50000",
     "gridPos": { "h": 1, "w": 1, "x": 2, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(trcnt_stat_res{range=~\"(\\\\^31000|\\\\^50000)\",network=\"$net\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Profile indexes",
     "type": "timeseries",
     "description": "3",
     "gridPos": { "h": 1, "w": 1, "x": 3, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "trcnt_stat_res{range=\"3\",network=\"$net\"}",
       "legendFormat": " "
      }
     ]
    }
   ]
  }
 ]
}