pipeline {
	agent {
        docker {
            image 'jenkins-docker-agent:1'
            args '-v /var/run/docker.sock:/var/run/docker.sock -v /tmp/giver.keys.json:/tmp/giver.keys.json --group-add docker'
        }  
    }
    parameters {
        gitParameter branchFilter: 'origin/(.*)', defaultValue: 'contracts/fix-bugs', name: 'BRANCH', type: 'PT_BRANCH', quickFilterEnabled: true
    }

    stages {
        failFast true
        stage('Clone repository') {
            steps {
                git branch: "${params.BRANCH}", url: 'https://github.com/gosh-sh/gosh.git'
                checkout scm
                script {
                    env.VERSION = sh script: "cat git-remote-gosh/Cargo.toml | grep version | head -1 | grep -Eo '[0-9]\\.[0-9]\\.[0-9]' | tr -d '\n'", returnStdout: true
                    currentBuild.displayName = "#${BUILD_NUMBER}_${BRANCH}_v${VERSION}"
                }
            }
        }   

        stage('Compile') { 
            stages {
                stage("Compile: SMV") {
                    steps {
                        script {
                            dir ('contracts/smv') {
                                sh 'make build-contracts'
                            }
                        }
                    }
                }
                stage("Compile: GOSH") {
                    steps {
                        script {
                            dir ('contracts/gosh') {
                                sh 'make build-contracts'
                            }
                        }
                    }
                }
            }
        }

        parallel {
            stage('Build') { 
                stages {
                    stage("Build: Git Helper") {
                        steps {
                            script {
                                dir ('git-remote-gosh') {
                                    sh "make bench FULL_IMAGE_NAME=teamgosh/git:${VERSION} PLATFORM=linux/amd64,linux/arm64"
                                }
                            }
                        }
                    }
                    stage("Build: Docker Extension") {
                        steps {
                            script {
                                dir ('docker-extension') {
                                    sh "make build-ci IMAGE=teamgosh/docker-extension TAG=${VERSION} GOSH_GIT_IMAGE=teamgosh/git:${VERSION}"
                                }
                            }
                        }
                    }
                }
            }

            stage("Deploy: smart-contracts") {
                steps {
                    script {
                        dir ('contracts/gosh') {
                            sh 'make prepare-docker && make deploy-docker KEYS_PATH=/tmp/giver.keys.json NETWORK=vps23.ton.dev GIVER_WALLET_ADDR=0:c6f86566776529edc1fcf3bc444c2deb9f3e077f35e49871eb4d775dd0b04391'
                        }
                    }
                    archiveArtifacts artifacts: "contracts/gosh/gosh.seed"
                }
            }
        }

        stage('Publish') { 
            stages {
                stage("Publish: Git Helper") {
                    steps {
                        script {
                            dir ('git-remote-gosh') {
                                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'teamgosh-dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                                    sh 'docker login -u $USERNAME -p $PASSWORD'
                                }
                                sh "make publish FULL_IMAGE_NAME=teamgosh/git:${VERSION} PLATFORM=linux/amd64,linux/arm64"
                            }
                        }
                    }   
                }
                /*stage("Publish: Docker Extension") {
                    steps {
                        script {
                            dir ('docker-extension') {
                                sh "make publish IMAGE=teamgosh/docker-extension TAG=${VERSION} GOSH_GIT_IMAGE=teamgosh/git:${VERSION}"
                            }
                        }
                    }
                }*/
            }
        }  
    }
    post { 
        always { 
            cleanWs()
        }
    }
}