version: '3.8'

services:
  redis:
    container_name: redis
    image: redis
    restart: always

  send_email:
    image: gosh-onboarding
    restart: always
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      REDIS_URL: redis://redis:6379
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
    command: >
      deno run -A ./src/send_email_scheduler.ts

  create_dao_bot:
    image: gosh-onboarding
    restart: always
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      REDIS_URL: redis://redis:6379
    command: >
      deno run -A ./src/create_dao_bot_scheduler.ts

  create_dao:
    image: gosh-onboarding
    restart: always
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      REDIS_URL: redis://redis:6379
    command: >
      deno run -A ./src/create_dao_scheduler.ts
