version: '3.8'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379

  send_email:
    image: gosh-onboarding
    restart: always
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      REDIS_HOST: ${REDIS_HOST}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
    command: >
      deno run -A src/emails.ts

  dao_bot:
    image: gosh-onboarding
    restart: always
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      REDIS_HOST: ${REDIS_HOST}
    command: >
      deno run -A src/emails.ts
