- _: config
  appurl: https://gosh-web-x-x-xx.gosh.sh/
  organization: testxxx-monit-org
  repository: testxxx-monit-repo
  timeout: 60000
  longtimeout: 3600000
- seed-read
- root-check
- app-setup
- app-small-write
- app-small-read
- app-large-write
- app-large-read
