- _: config
  # Need to set unique using environment or config
  # appurl: https://gosh-web-x-x-xx.gosh.sh/
  # organization: monitoring-org-test-xxx
  # repository: monitoring-org-repo-xxx
  timeout_ms: 60000
  longtimeout_ms: 3600000
  redis_host: ""
- seed-read
- app-setup
- app-small-write
- app-small-read
- app-large-write
- app-large-read
