variables:
- name: RUSTUP_TOOLCHAIN
  value: 1.66.0 

trigger: none

strategy:
  matrix:
    linux:
      imageName: ubuntu-20.04
      artifactName: linux-amd64
    mac:
      imageName: macOS-12
      artifactName: darwin-amd64
    windows:
      imageName: windows-2019
      artifactName: windows-amd64
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
# Pre-requirements
# Linux
- script: |
    sudo apt install -y protobuf-compiler
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: Install pre-requirements Linux
# Mac
- script: |
    brew install protobuf
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: Install pre-requirements MacOS
# Windows
- script: |
    choco install protoc
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: Install pre-requirements Windows

# Rust setup
# Linux and macOS
- script: |
    set -e
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  env:
    RUSTUP_TOOLCHAIN: ${{ variables.RUSTUP_TOOLCHAIN }}
  displayName: "Install rust (*nix)"
  condition: not(eq(variables['Agent.OS'], 'Windows_NT'))
# Windows
- script: |
    curl -sSf -o rustup-init.exe https://win.rustup.rs
    rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
    set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
  env:
    RUSTUP_TOOLCHAIN: ${{ variables.RUSTUP_TOOLCHAIN }}
  displayName: "Install rust (windows)"
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  
# Build
- script: |
    mkdir -p ./resources
    cp ../contracts/gosh/*.abi.json ./resources/
  workingDirectory: git-remote-gosh
  displayName: Prepare resources
   
- script: |
    cargo build --release
  workingDirectory: git-remote-gosh
  displayName: Build git-remote-gosh

# Check version
- bash: |
    chmod +x ./git-remote-gosh_unknown
    VERSION=$(./git-remote-gosh_unknown supported_contract_version | cut -d '"' -f 2 | sed "s/\./_/g")
    echo $VERSION
    echo "##vso[task.setvariable variable=VERSION]$VERSION"
  workingDirectory: git-remote-gosh/target/release
  displayName: Get supported_contract_version
  condition: eq(variables['Agent.OS'], 'Linux')

# Set Version
# Linux and macOS
- bash: |
    echo git-remote-gosh_v$(VERSION)
    mv git-remote-gosh_unknown git-remote-gosh_v$(VERSION)
  workingDirectory: git-remote-gosh/target/release
  displayName: Name binaries 
  condition: not(eq(variables['Agent.OS'], 'Windows_NT'))

# Windows
- bash: |
    mv git-remote-gosh_unknown.exe git-remote-gosh_v$(VERSION).exe
  workingDirectory: git-remote-gosh/target/release
  displayName: Name binaries 
  condition: eq(variables['Agent.OS'], 'Windows_NT')

# Publish
# Linux and macOS
- publish: ./git-remote-gosh/target/release/git-remote-gosh_v$(VERSION)
  artifact: $(artifactName)
  condition: not(eq(variables['Agent.OS'], 'Windows_NT'))

# Windows
- publish: ./git-remote-gosh/target/release/git-remote-gosh_v$(VERSION).exe
  artifact: $(artifactName)
  condition: eq(variables['Agent.OS'], 'Windows_NT')