variables:
- name: RUSTUP_TOOLCHAIN
  value: 1.70.0

trigger: none
pr: none

strategy:
  matrix:
    linux:
      imageName: ubuntu-20.04
      binName: git-remote-gosh
      artifactNameAmd: linux-amd64
    mac:
        imageName: macOS-12
        binName: git-remote-gosh
        artifactNameAmd: darwin-amd64
    windows:
        imageName: windows-2019
        binName: git-remote-gosh.exe
        artifactNameAmd: windows-amd64
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
#######################################################
# Pre-requirements
# Linux
- script: |
    set -ex
    sudo apt install -y protobuf-compiler
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: Install pre-requirements Linux
# Mac
- script: |
    brew install protobuf
  condition: and(eq(variables['Agent.OS'], 'Darwin'), eq(variables['DRYRUN'], 'false'))
  displayName: Install pre-requirements MacOS
# Windows
- script: |
    choco install protoc
  condition: and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['DRYRUN'], 'false'))
  displayName: Install pre-requirements Windows

###########################################################
# Rust setup
# Linux and macOS
- script: |
    set -ex
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  env:
    RUSTUP_TOOLCHAIN: ${{ variables.RUSTUP_TOOLCHAIN }}
  displayName: "Install rust (*nix)"
  condition: not(eq(variables['Agent.OS'], 'Windows_NT'))
# Windows
- script: |
    curl -sSf -o rustup-init.exe https://win.rustup.rs
    rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
    set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
  env:
    RUSTUP_TOOLCHAIN: ${{ variables.RUSTUP_TOOLCHAIN }}
  displayName: "Install rust (windows)"
  condition: and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['DRYRUN'], 'false'))

##########################################################
# Build
# Linux
- script: |
    set -ex
    sudo apt update -y
    cargo build --release
  workingDirectory: gosh-dispatcher
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: Build Linux amd
# Linux
- script: |
    set -ex
    sudo apt update -y
    sudo apt install -y build-essential g++-x86-64-linux-gnu libc6-dev-amd64-cross g++-aarch64-linux-gnu libc6-dev-arm64-cross gcc-aarch64-linux-gnu
    rustup target add aarch64-unknown-linux-gnu
    cargo build --release --target aarch64-unknown-linux-gnu
  env:
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: x86_64-linux-gnu-gcc
    CC_x86_64_unknown_linux_gnu: x86_64-linux-gnu-gcc
    CXX_x86_64_unknown_linux_gnu: x86_64-linux-gnu-g++
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
    CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
    CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++
  workingDirectory: gosh-dispatcher
  condition: and(eq(variables['Agent.OS'], 'Linux'), eq(variables['DRYRUN'], 'false'))
  displayName: Build Linux arm
# Mac
- script: |
    set -ex
    cargo build --release
    rustup target add aarch64-apple-darwin
    cargo build --release --target aarch64-apple-darwin
  workingDirectory: gosh-dispatcher
  condition: and(eq(variables['Agent.OS'], 'Darwin'), eq(variables['DRYRUN'], 'false'))
  displayName: Build MacOS
# Windows
- script: |
    cargo build --release
  workingDirectory: gosh-dispatcher
  condition: and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['DRYRUN'], 'false'))
  displayName: Build Windows

##################################
# Publish 
# Linux, MacOs and Windows amd64 
- publish: ./gosh-dispatcher/target/release/$(binName)
  artifact: $(artifactNameAmd)
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: Publish amd64 Linux

- publish: ./gosh-dispatcher/target/release/$(binName)
  artifact: $(artifactNameAmd)
  condition: and(eq(variables['Agent.OS'], 'Darwin'), eq(variables['DRYRUN'], 'false'))
  displayName: Publish amd64 Mac

- publish: ./gosh-dispatcher/target/release/$(binName)
  artifact: $(artifactNameAmd)
  condition: and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['DRYRUN'], 'false'))
  displayName: Publish amd64 Windows

# Linux arm64
- publish: ./gosh-dispatcher/target/aarch64-unknown-linux-gnu/release/$(binName)
  artifact: linux-arm64
  condition: and(eq(variables['Agent.OS'], 'Linux'), eq(variables['DRYRUN'], 'false'))
  displayName: Publish arm64 Linux

# MacOS arm64
- publish: ./gosh-dispatcher/target/aarch64-apple-darwin/release/$(binName)
  artifact: darwin-arm64
  condition: and(eq(variables['Agent.OS'], 'Darwin'), eq(variables['DRYRUN'], 'false'))
  displayName: Publish arm64 MacOS