[[bin]]
name = 'git-remote-gosh_unknown'
path = 'src/bin/main.rs'

[lib]
exclude = 'src/bin/*'
name = 'git_remote_gosh'
path = 'src/lib.rs'

[package]
build = 'build.rs'
edition = '2021'
keywords = ['git-remote', 'git', 'gosh']
name = 'git-remote-gosh'
resolver = '2'
rust-version = "1.65"
version = '3.0.10'

[profile.profiling]
debug = 1
inherits = 'release'

[dev-dependencies]
mockall = '^0'

[dependencies]
anyhow = '^1.0'
async-trait = '^0'
base64 = '^0.21.0'
base64-serde = '^0.7.0'
bytes = '^1'
cached = {version = '^0.38.0', features = ['default']}
clap = "4.1"
derive_builder = '^0.11'
form-data = '^0'
futures = '^0'
git-diff = '^0'
git-hash = '^0'
git-object = '^0'
git-odb = '^0'
git-repository = '^0'
git-revision = '^0'
git-traverse = '^0'
hex = '^0'
indexmap = '^1'
lru = '^0.8.1'
memcache = '^0.17.0'
mockall_double = '^0'
object-pool = "0.5.4"
once_cell = "^1.16.0"
openssl = {version = '0.10', features = ['vendored']}
opentelemetry = {version = "0.18.0", features = ["rt-tokio"]}
opentelemetry-otlp = {version = "0.11.0", features = ["grpc-tonic"]}
opentelemetry-semantic-conventions = "0.10.0"
primitive-types = '^0.12'
reqwest-middleware = "0.2.0"
reqwest-tracing = "0.4.0"
serde_json = '^1.0'
sha256 = '1.0.3'
shellexpand = '^2.1.0'
thiserror = '^1.0.38'
tokio-retry = '^0'
tracing = "0.1"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = {version = "0.3.16", features = ["env-filter"]}
tracing-test = "0"

[dependencies.data-contract-macro-derive]
path = 'crates/data-contract-macro-derive'

[dependencies.diffy]
path = 'crates/diffy-patched'

[dependencies.serde]
features = ['derive']
version = '^1'

[dependencies.tracing-futures]
default-features = true
version = '^0'

[dependencies.reqwest]
features = ['blocking', 'gzip', 'json', 'multipart', 'stream']
version = '^0'

[dependencies.tokio]
features = ['full', 'rt']
version = '1.21.2'

[dependencies.ton_client]
git = 'https://github.com/tonlabs/ever-sdk.git'
package = 'ton_client'
rev = '13eb9bfd8e7553c5551b497b5c66542c742c0c1a'

[dependencies.ton_sdk]
git = 'https://github.com/tonlabs/ever-sdk.git'
package = 'ton_sdk'
rev = '13eb9bfd8e7553c5551b497b5c66542c742c0c1a'

[dependencies.zstd]
default-features = false
version = '^0.11.0'

[patch.crates-io.tokio]
git = 'https://github.com/tokio-rs/tokio'
tag = 'tokio-1.21.2'

