[env]
CONTRACTS_DIR = { value = "../contracts/gosh/", relative = true }

[alias]
lint = "clippy --workspace --tests --examples --bins -- -Dclippy::todo"
lint-all = "clippy --workspace --all-features --tests --examples --bins -- -Dclippy::todo"
