global:
  seed:          ###SECRET###
  organization:  monitoring
  repository:    monitoring
  branch:        INVALID
  filename:      last
  handler:       INVALID
  large:         false
  prefix:        gosh_mon_
  timeout:       20000
  root:          0:457cd81c98f745217825d8c955973a5b0149babc27228b6e90658ffe7e84b01e
  interval:      45
  subinterval:   0
  origin:        INVALID
  cron:          false
  appurl:        https://app.gosh.sh/
  pupextraflags: []
  gosh_repo_url: https://github.com/gosh-sh/gosh.git
  gosh_branch:   "release:latest"
  gosh_bin_path: last-git-remote-gosh
  release_asset: git-remote-gosh-amd64


includes:

  next: &next
    appurl: https://next-app.monitoring.gosh.sh/


modes:

  seed-read:
    handler: seed-read

  root-check:
    handler: root-check

# app.gosh.sh
  app-small-read: &app-small-read
    branch:  ticker-app-small
    handler: app-read
    large:   false

  app-small-write: &app-small-write
    branch:  ticker-app-small
    handler: app-write
    large:   false
    interval: 200

  app-large-read: &app-large-read
    branch:  ticker-app-large
    handler: app-read
    large:   true
    timeout: 15000

  app-large-write: &app-large-write
    branch:  ticker-app-large
    handler: app-write
    large:   true
    timeout: 15000
    interval: 450

  app-small-read-next:
    <<: *app-small-read
    <<: *next

  app-small-write-next:
    <<: *app-small-write
    <<: *next

  app-large-read-next:
    <<: *app-large-read
    <<: *next

  app-large-write-next:
    <<: *app-large-write
    <<: *next

# git-remote-gosh
  rem-small-read: &rem-small-read
    branch:  ticker-remote-small
    handler: remote-read
    large:   false
    timeout: 50

  rem-small-write: &rem-small-write
    branch:  ticker-remote-small
    handler: remote-write
    large:   false
    interval: 150
    timeout: 270

  rem-large-read: &rem-large-read
    branch:  ticker-remote-large
    handler: remote-read
    large:   true
    timeout: 50

  rem-large-write: &rem-large-write
    branch:  ticker-remote-large
    handler: remote-write
    large:   true
    interval: 450
    timeout: 270
