declare const _exports: {
    aiAssistant: string;
    aiCommands: string;
    'AI Assistant': string;
    'AI Commands': string;
    'Improve writing': string;
    'Make shorter': string;
    'Make longer': string;
    'Simplify language': string;
    Summarize: string;
    Continue: string;
    Prompt: string;
    Insert: string;
    'Insert After': string;
    'Try Again': string;
    'Ask AI to improve generated text': string;
    'Change tone to professional': string;
    'Change tone to friendly': string;
    'Change tone to formal': string;
    'Change tone to casual': string;
    'Change tone to direct': string;
    'Change tone to confident': string;
    'Change tone to business': string;
    'Change style to legal': string;
    'Change style to journalism': string;
    'Change style to poetic': string;
    'Translate to Spanish': string;
    'Translate to French': string;
    'Translate to German': string;
    'Translate to Italian': string;
    'Translate to Portuguese': string;
    'Translate to English': string;
    'Translate to Chinese': string;
    'Translate to Japanese': string;
    'Translate to Korean': string;
    'Translate to Russian': string;
    'Translate to Arabic': string;
    Submit: string;
};
export = _exports;
